export type Transaction = {
  transactionId: string;
  customerId: string;
  transactionType: 'sale' | 'purchase' | 'expense' | 'refund';
  amount: number;
  currency: string;
  transactionDate: Date;
  paymentMethod: 'cash' | 'credit card' | 'bank transfer' | 'online payment';
  status: 'pending' | 'completed' | 'failed';
  productId?: string;
  quantity?: number;
  unitPrice?: number;
  vendorId?: string;
  invoiceNumber?: string;
  taxAmount?: number;
  discounts?: number;
  shippingCost?: number;
  employeeId?: string;
  location?: string;
};