import { Transaction } from "@/types/transaction";

export const transactions: Transaction[] = [
  {
    transactionId: 'TXN10001',
    customerId: 'CUST100',
    transactionType: 'sale',
    amount: 200.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-01T09:00:00Z'),
    paymentMethod: 'credit card',
    status: 'completed',
    productId: 'PROD101',
    quantity: 2,
    unitPrice: 100.0,
    taxAmount: 30.0,
    discounts: 10.0,
    shippingCost: 5.0,
    employeeId: 'EMP001',
    location: 'Outlet 1'
  },
  {
    transactionId: 'TXN10002',
    customerId: 'CUST101',
    transactionType: 'purchase',
    amount: 150.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-02T10:00:00Z'),
    paymentMethod: 'bank transfer',
    status: 'pending',
    vendorId: 'VEND100',
    taxAmount: 15.0,
    shippingCost: 20.0,
    employeeId: 'EMP002',
    location: 'Outlet 2'
  },
  {
    transactionId: 'TXN10003',
    customerId: 'CUST102',
    transactionType: 'expense',
    amount: 50.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-03T11:00:00Z'),
    paymentMethod: 'cash',
    status: 'completed',
    employeeId: 'EMP003',
    location: 'Headquarters'
  },
  {
    transactionId: 'TXN10004',
    customerId: 'CUST103',
    transactionType: 'refund',
    amount: 75.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-04T12:00:00Z'),
    paymentMethod: 'credit card',
    status: 'completed',
    productId: 'PROD102',
    quantity: 1,
    unitPrice: 75.0,
    employeeId: 'EMP004',
    location: 'Outlet 3'
  },
  {
    transactionId: 'TXN10005',
    customerId: 'CUST104',
    transactionType: 'sale',
    amount: 120.0,
    currency: 'EUR',
    transactionDate: new Date('2024-05-05T13:00:00Z'),
    paymentMethod: 'online payment',
    status: 'failed',
    productId: 'PROD103',
    quantity: 4,
    unitPrice: 30.0,
    taxAmount: 20.0,
    discounts: 5.0,
    shippingCost: 10.0,
    employeeId: 'EMP005',
    location: 'Outlet 4'
  },
  {
    transactionId: 'TXN10006',
    customerId: 'CUST105',
    transactionType: 'sale',
    amount: 180.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-06T14:00:00Z'),
    paymentMethod: 'credit card',
    status: 'completed',
    productId: 'PROD104',
    quantity: 3,
    unitPrice: 60.0,
    taxAmount: 27.0,
    discounts: 10.0,
    employeeId: 'EMP006',
    location: 'Outlet 5'
  },
  {
    transactionId: 'TXN10007',
    customerId: 'CUST106',
    transactionType: 'purchase',
    amount: 200.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-07T15:00:00Z'),
    paymentMethod: 'bank transfer',
    status: 'completed',
    vendorId: 'VEND101',
    taxAmount: 20.0,
    shippingCost: 15.0,
    employeeId: 'EMP007',
    location: 'Outlet 1'
  },
  {
    transactionId: 'TXN10008',
    customerId: 'CUST107',
    transactionType: 'expense',
    amount: 90.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-08T16:00:00Z'),
    paymentMethod: 'cash',
    status: 'completed',
    employeeId: 'EMP008',
    location: 'Headquarters'
  },
  {
    transactionId: 'TXN10009',
    customerId: 'CUST108',
    transactionType: 'refund',
    amount: 50.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-09T17:00:00Z'),
    paymentMethod: 'credit card',
    status: 'completed',
    productId: 'PROD105',
    quantity: 1,
    unitPrice: 50.0,
    employeeId: 'EMP009',
    location: 'Outlet 2'
  },
  {
    transactionId: 'TXN10010',
    customerId: 'CUST109',
    transactionType: 'sale',
    amount: 300.0,
    currency: 'USD',
    transactionDate: new Date('2024-05-10T18:00:00Z'),
    paymentMethod: 'online payment',
    status: 'completed',
    productId: 'PROD106',
    quantity: 5,
    unitPrice: 60.0,
    taxAmount: 45.0,
    discounts: 15.0,
    shippingCost: 25.0,
    employeeId: 'EMP010',
    location: 'Outlet 3'
  }
]
